# This formula is auto-generated by the TWG CLI release pipeline.
# Do not edit manually — changes will be overwritten on next release.
#
# Source: bin/release/package-homebrew.sh in https://bitbucket.org/atlassian/twg-cli

class Twg < Formula
  desc "CLI wrapper for the Atlassian TeamWork Graph API"
  homepage "https://bitbucket.org/atlassian/twg-cli"
  license "MIT"
  version "0.0.0"

  # Placeholder formula — will be replaced by the first automated release.
  # See RELEASE.md in the main repo for the release process.

  if OS.mac?
    if Hardware::CPU.arm?
      url "https://statlas.prod.atl-paas.net/community-assets-twg/clis/external/0.0.0/homebrew/twg-darwin-arm64.tar.gz"
      sha256 "PLACEHOLDER"
    elsif Hardware::CPU.intel?
      url "https://statlas.prod.atl-paas.net/community-assets-twg/clis/external/0.0.0/homebrew/twg-darwin-x64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  elsif OS.linux?
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://statlas.prod.atl-paas.net/community-assets-twg/clis/external/0.0.0/homebrew/twg-linux-arm64.tar.gz"
      sha256 "PLACEHOLDER"
    elsif Hardware::CPU.intel?
      url "https://statlas.prod.atl-paas.net/community-assets-twg/clis/external/0.0.0/homebrew/twg-linux-x64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  else
    odie "twg is not supported on this platform"
  end

  def install
    bin.install "twg"
  end

  test do
    output = shell_output("#{bin}/twg --version")
    assert_match version.to_s, output
  end
end
